export const radioButtons = [
  { id: 1, label: "Frontend", name: "tool" },
  { id: 2, label: "Backend", name: "tool" },
  { id: 3, label: "Devops", name: "tool" },
  { id: 4, label: "Testing", name: "tool" },
  { id: 5, label: "UX/UI", name: "tool" },
  { id: 6, label: "Infrastructure", name: "tool" },
  { id: 7, label: "Mobile", name: "tool" },
];

export const tools = [
  { id: 1, title: "Promotheus", image: "", status: "Devops" },
  { id: 2, title: "Promotheus", image: "", status: "Devops" },
  { id: 3, title: "Promotheus", image: "", status: "Devops" },
  { id: 4, title: "Promotheus", image: "", status: "Devops" },
  { id: 5, title: "Promotheus", image: "", status: "Devops" },
  { id: 6, title: "Promotheus", image: "", status: "Devops" },
  { id: 7, title: "Promotheus", image: "", status: "Devops" },
  { id: 8, title: "Promotheus", image: "", status: "Backend" },
  { id: 9, title: "Promotheus", image: "", status: "Backend" },
  { id: 10, title: "Promotheus", image: "", status: "Backend" },
  { id: 11, title: "Promotheus", image: "", status: "Backend" },
  { id: 12, title: "Promotheus", image: "", status: "Backend" },
  { id: 13, title: "Promotheus", image: "", status: "Backend" },
  { id: 14, title: "Promotheus", image: "", status: "Backend" },
  { id: 15, title: "Promotheus", image: "", status: "Frontend" },
  { id: 16, title: "Promotheus", image: "", status: "Frontend" },
  { id: 17, title: "Promotheus", image: "", status: "Frontend" },
  { id: 18, title: "Promotheus", image: "", status: "Frontend" },
  { id: 19, title: "Promotheus", image: "", status: "Frontend" },
  { id: 20, title: "Promotheus", image: "", status: "Frontend" },
  { id: 21, title: "Promotheus", image: "", status: "Frontend" },
  { id: 22, title: "Promotheus", image: "", status: "Testing" },
  { id: 23, title: "Promotheus", image: "", status: "Testing" },
  { id: 24, title: "Promotheus", image: "", status: "Testing" },
  { id: 25, title: "Promotheus", image: "", status: "Testing" },
  { id: 26, title: "Promotheus", image: "", status: "Testing" },
  { id: 27, title: "Promotheus", image: "", status: "Testing" },
  { id: 28, title: "Promotheus", image: "", status: "Testing" },
  { id: 29, title: "Promotheus", image: "", status: "UX/UI" },
  { id: 30, title: "Promotheus", image: "", status: "UX/UI" },
  { id: 31, title: "Promotheus", image: "", status: "UX/UI" },
  { id: 32, title: "Promotheus", image: "", status: "UX/UI" },
  { id: 33, title: "Promotheus", image: "", status: "UX/UI" },
  { id: 34, title: "Promotheus", image: "", status: "UX/UI" },
  { id: 35, title: "Promotheus", image: "", status: "UX/UI" },
  { id: 36, title: "Promotheus", image: "", status: "Infrastructure" },
  { id: 37, title: "Promotheus", image: "", status: "Infrastructure" },
  { id: 38, title: "Promotheus", image: "", status: "Infrastructure" },
  { id: 39, title: "Promotheus", image: "", status: "Infrastructure" },
  { id: 40, title: "Promotheus", image: "", status: "Infrastructure" },
  { id: 41, title: "Promotheus", image: "", status: "Infrastructure" },
  { id: 42, title: "Promotheus", image: "", status: "Mobile" },
  { id: 43, title: "Promotheus", image: "", status: "Mobile" },
  { id: 44, title: "Promotheus", image: "", status: "Mobile" },
  { id: 45, title: "Promotheus", image: "", status: "Mobile" },
  { id: 46, title: "Promotheus", image: "", status: "Mobile" },
  { id: 47, title: "Promotheus", image: "", status: "Mobile" },
  { id: 48, title: "Promotheus", image: "", status: "Mobile" },
];
